language: node_js
node_js:
- node
cache: npm
script: npm run deploy
after_script: npm run alias
env:
  global:
    secure: o9R7wWTnJMYdu2pRZ4LrdxSKixDIF+crPhrTUWelmzmTbGEyXOMsOoA9TtW+4w0CwoJmHOtbN5kEYnYs+iWALiHuEguBH3N5Jg1HWxF/b92g0HtKxOCBAS+PuPQug4G0dBUt/eDNN/rg2LRDn1IwXdNr/KeURHX5kZkJvgc9tv82f3uyUimnjmLlQdTfQr354kq/Wy82Bm3sY1u2BbWN+WWviPAPeNTfDdDsbbEIW6Zvbp0FjsKPThjs7VLmNB2RtG259U69fajHTRxONDjMx9f0WHZDpN5XkjnbZ47ejYoxojjf3NjD33CAMbOBTVuLt9UDrbKbKW90Urj5ufhhHWs7P6JdYmFLKggsCiHJSF1FQLN5uz/USMvQuugDC9v8kgZSOZeaatMzdII9df8fjb9szF6YrrNVL48nJY70YzaoF/ENAA8+9iYwT1n8uhAVDqFEntK4tOEImJ7+mzT4hcBL7MB/MTu8QwLju9Q+Ql5QNC054RtABlaXuEcuuhweZnLfYqEQi/BtL2gi5SlX0VWHJ55YwNPuEpNFWUasPHT/TaTZWRWSDmmbNsI0mzGQ/KRdmVWEE2dMqa08b4/qT1TZqcMlRAM+fUZqlKuxatYxHHn3FP3UwAbm5iuiczWxKRCpSpzOBEp9/KhrLhSaiJ0BoTBoztKg64WA4L8WCZ0=
